name: CI/CD

on:
    push:
        branches:
            - master
            - main
    pull_request:
        branches:
            - master
            - main


jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: 
              uses: actions/setup-python@v5 
              with:
                  python-version: '3.11' 
            - run: pip install --upgrade pip && pip install -r requirements.txt
            - run : pytest
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: false
                tags: ghcr.io/${{ github.repository }}:latest

            
    

